name: Java CI/CD with Gradle

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    
    - name: Checkout repo
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Gradle Wrapper
      run: chmod +x ./gradlew; ./gradlew build

    - name: Upload artifact (JAR file)
      uses: actions/upload-artifact@v4
      with:
        name: demo-jar
        path: build/libs/demo-0.0.1-SNAPSHOT.jar

  deploy:
  
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      
    steps:
    
    - name: Download artifact (JAR file)
      uses: actions/download-artifact@v4
      with:
        name: demo-jar  # Le nom de l'artefact que nous avons uploadé dans le job build
        
    - name: Publish to server
      uses: appleboy/scp-action@master
      with:
        host: 188.245.157.167
        username: root
        password: totonono
        source: "/home/runner/work/DemoJava_CI_CD/DemoJava_CI_CD/demo-0.0.1-SNAPSHOT.jar"
        target: /home/quentin/

    - name: Restart app in server
      uses: appleboy/ssh-action@master
      with:
        host: 188.245.157.167
        username: root
        password: totonono
        command_timeout: 30m
        script: sudo systemctl restart quentin.service 
